from typing import Optional, Protocol, runtime_checkable


@runtime_checkable
class AuthSessionDao(Protocol):
    async def store_refresh_token(self, token: str, user_id: int, ttl: int) -> None: ...

    async def get_user_id_by_refresh_token(self, token: str) -> Optional[int]: ...

    async def revoke_refresh_token(self, token: str) -> None: ...

    async def get_and_revoke_refresh_token(self, token: str) -> Optional[int]: ...

    async def revoke_all_user_tokens(self, user_id: int) -> None: ...

    async def store_password_reset_token(self, token_hash: str, user_id: int, ttl: int) -> None: ...

    async def consume_password_reset_token(self, token_hash: str) -> Optional[int]: ...

    async def revoke_password_reset_token(self, token_hash: str) -> None: ...

    async def try_start_password_reset_cooldown(self, email_hash: str, ttl: int) -> bool: ...

    async def clear_password_reset_cooldown(self, email_hash: str) -> None: ...
