from typing import Protocol, runtime_checkable


@runtime_checkable
class WaitlistDao(Protocol):
    async def is_in_waitlist(self, telegram_id: int) -> bool: ...

    async def add_to_waitlist(self, telegram_id: int) -> None: ...

    async def get_waitlist_members(self) -> list[int]: ...

    async def clear_waitlist(self) -> None: ...
