from typing import Optional, Protocol, Union

from src.application.dto import UserDTO
from src.core.enums import UserRole


class UserDAO(Protocol):
    async def create(self, user: UserDTO) -> UserDTO: ...

    async def get(self, telegram_id: int) -> Optional[UserDTO]: ...

    async def get_by_ids(self, telegram_ids: list[int]) -> list[UserDTO]: ...

    async def get_by_partial_name(self, query: str) -> list[UserDTO]: ...

    async def get_all(self, limit: int = 100, offset: int = 0) -> list[UserDTO]: ...

    async def exists(self, telegram_id: int) -> bool: ...

    async def update(self, user: UserDTO) -> Optional[UserDTO]: ...

    async def delete(self, telegram_id: int) -> bool: ...

    async def count(self) -> int: ...

    async def filter_by_role(self, role: Union[UserRole, list[UserRole]]) -> list[UserDTO]: ...
